textsPath: 'texts_en.yml'

# world guard flag to check against for editing displays. default: BUILD
worldguardFlag: 'BUILD'

autoFocusDisplayOnGUI: true # whether to turn the player's camera for /display gui
GUIYawOffsetTarget: 50 # degrees



# base scales for transforms
positionScale: 0.01
rotationScale:  1.0
sizeScale: 0.01
brightnessScale: 0.01
multiplierFastSpeed: 10.0
multiplierSlowSpeed: 0.1

maxDisplaySize: 20.0
minDisplaySize: 0.01

# text displays
minTextDisplayOpacity: 0.1

# time between display edits before unselecting display
playerStaleTime: 300
playerCleanupFrequency: 600

# allow display group commands (default: false)
doDisplayGroups: true
doDisplayGroupRotation: false
doDisplayGroupShow: true
doArmorStandConversion: false

# furthest distance to search when looking for nearby displays (default: 16)
# high values might affect performance in large areas with a lot of displays
maxSearchRadius: 16

# how deep to search for descendants in display group trees before giving up?
maxSearchDepth: 10