name: displayer
version: '${project.version}'
main: me.vivian.displayer.EventListeners
api-version: '1.20'

commands:
  display:
    description: Main command for managing displays
    usage: /display create | closest [radius] | nearby [radius] | destroy [<nearby> [maxCount] [radius]] | gui | help
    aliases:
      - displayer
    subcommands:
      create:
        description: Create a new display
        usage: /display create <item | block> [atSelected]
      nearby:
        description: List nearby displays
        usage: /display nearby [radius = 5]
      closest:
        description: select the closest display
        usage: /display closest [radius = 5]
      destroy:
        description: Destroy display(s)
        usage: /display destroy [<nearby> [maxCount = 1] [radius = 5]]
      gui:
        description: Open a graphical user interface for display management
        usage: /display gui
      help:
        description: Display plugin help
        usage: /display help

  advdisplay:
    description: Advanced display manipulation commands
    usage: /advdisplay select <index> | setrotation <yaw> <pitch> [roll] | changerotation <yawOffset> <pitchOffset> [rollOffset] | setposition <x> <y> <z> | changeposition <xOffset> <yOffset> <zOffset> | setsize <size> | changesize <sizeOffset>
    subcommands:
      select:
        description: Select a display by index
        usage: /advdisplay select <index>
      setrotation:
        description: Set rotation for the selected display
        usage: /advdisplay setrotation <yaw> <pitch> [roll]
      changerotation:
        description: Change rotation for the selected display
        usage: /advdisplay changerotation <yawOffset> <pitchOffset> [rollOffset]
      setposition:
        description: Set position for the selected display
        usage: /advdisplay setposition <x> <y> <z>
      changeposition:
        description: Change position for the selected display
        usage: /advdisplay changeposition <xOffset> <yOffset> <zOffset>
      setsize:
        description: Set size for the selected display
        usage: /advdisplay setsize <size>
      changesize:
        description: Change size for the selected display
        usage: /advdisplay changesize <sizeOffset>
      rename:
        description: Set the name for a given display
        usage: /display rename <name>
      details:
        description: gives you the details of your selected display
        usage: /advdisplay details

  displaygroup:
    description: Commands for handling grouped displays
    usage: /displaygroup parent <parentName> | unparent | copypaste | show | rotate <yaw> <pitch> <roll> | translate <xTranslation> <yTranslation> <zTranslation>
    subcommands:
      parent:
        description: Sets the parent of the selected display
        usage: /displaygroup parent <parentName>
      unparent:
        description: Unsets the parent of the selected display
        usage: /displaygroup unparent
      copypaste:
        description: Copies and pastes the hierarchy of the selected display at the player's current location
        usage: /displaygroup copypaste
      rotate:
        description: Rotates the hierarchy of the selected display
        usage: /displaygroup rotate <xRotation> <yRotation> <zRotation>
      translate:
        description: Translates the hierarchy of the selected display
        usage: /displaygroup translate <xTranslation> <yTranslation> <zTranslation>
      show:
        description: Highlights the displaygroup selected
        usage: /displaygroup show
