name: displayer
version: '${project.version}'
main: me.vivian.displayer.DisplayPlugin
api-version: '1.20'

# todo: ensure this is accurate still-

commands:
  display:
    description: Main command for managing displays
    usage: /display create | closest [radius] | nearby [radius] | destroy [<nearby> [maxCount] [radius]] | gui | help
    aliases:
      - displayer
    subcommands:
      create:
        description: Create a new display
        usage: /display create <item | block> [atSelected]
      nearby:
        description: List nearby displays
        usage: /display nearby [radius = 5]
      closest:
        description: select the closest display
        usage: /display closest [radius = 5]
      destroy:
        description: Destroy display(s)
        usage: /display destroy [<nearby> [maxCount = 1] [radius = 5]]
      gui:
        description: Open a graphical user interface for display management
        usage: /display gui
      help:
        description: Display plugin help
        usage: /display help
      rename:
        description: Set the name for a given display
        usage: /display rename <name>

  advdisplay:
    description: display commands the player shouldn't be entering directly
    usage: /advdisplay details | select <index>
    subcommands:
      select:
        description: Select a display by index
        usage: /advdisplay select <index>
      details:
        description: gives you the details of your selected display
        usage: /advdisplay details
      rename:
        description: renames a display
        usage: /advdisplay rename <name>

  displaygroup:
    description: Commands for handling grouped displays
    usage: /displaygroup parent <parentName> | unparent | copypaste | show | rotate <yaw> <pitch> <roll> | translate <xTranslation> <yTranslation> <zTranslation>
    subcommands:
      parent:
        description: Sets the parent of the selected display
        usage: /displaygroup parent <parentName>
      unparent:
        description: Unsets the parent of the selected display
        usage: /displaygroup unparent
      copypaste:
        description: Copies and pastes the hierarchy of the selected display at the player's current location
        usage: /displaygroup copypaste
      rotate:
        description: Rotates the hierarchy of the selected display
        usage: /displaygroup rotate <xRotation> <yRotation> <zRotation>
      translate:
        description: Translates the hierarchy of the selected display
        usage: /displaygroup translate <xTranslation> <yTranslation> <zTranslation>
      show:
        description: Highlights the displaygroup selected
        usage: /displaygroup show

  textdisplay:
    description: Commands for handling text displays
    usage: /textdisplay set <text <whatever text to set> | backgroundcolor <r> <g> <b> [a] | opacity <opacityValue>> | togglebackground | toggleshadow
    subcommands:
      set:
        description: sets various values for the textdisplay
        usage: /textdisplay set <text <whatever text to set> | backgroundcolor <r> <g> <b> [a] | opacity <opacityValue>>
      togglebackground:
        description: toggles text display background
        usage: /textdisplay togglebackground
      toggleshadow:
        description: toggles text display shadows
        usage: /textdisplay toggleshadow
